Update .travis.yml
As noted in https://travis-ci.org/github/ligurio/awesome-openbsd/builds/769979729

```$ gem install awesome_bot

Fetching: parallel-1.20.1.gem (100%)

ERROR:  Error installing awesome_bot:

	parallel requires Ruby version >= 2.4.´´´